version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce_postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net
    # Em produção, comente as portas para não expor o DB publicamente
    # ports:
    #   - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    restart: unless-stopped
    env_file:
      - ./ecommerce-backend-strapi/.env
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - backend_net
      - frontend_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    restart: unless-stopped
    env_file:
      - ./ecommerce-frontend-nextjs/.env
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend_net

volumes:
  postgres_data:


networks:
  backend_net:
  frontend_net:
